version: '3.7'
services:
  db:
    image: postgres:12.0
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_DB: rails6_docker
      POSTGRES_USER: rails6_docker_user
      POSTGRES_PASSWORD: somepassword
    volumes:
      - db-data:/var/lib/postgresql/data
    
  app:
    image: rails6_docker/production/app
    build:
      context: .
      dockerfile: docker/production/app/Dockerfile
    # command: bash -c "foreman start -f Procfile.dev-server"
    # command: rails server -p 3000 -b '0.0.0.0'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      # - 'web-data:/app'
      - '.:/app'
    ports:
      - '3000:3000'
    environment:
      # POSTGRES_DB: rails6_docker_development
      POSTGRES_USER: rails6_docker_user
      POSTGRES_PASSWORD: somepassword
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  web:
    image: rails6_docker/production/web
    build:
      context: .
      dockerfile: docker/production/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      # - web-data:/app
      - '.:/app'
    restart: always
volumes:
  db-data:
    name: rails6_docker_production_db_data
    driver: local
  # web-data:
  #   name: rails6_docker_production_web_data
  #   driver: local

networks:
  default:
    name: rails6_docker/production/default
    driver: bridge